### ISSUE TITLE
Реализовать корзину

### ISSUE THREAD

**Issue by mocki-toki** [mocki-toki/iOS-FakeNFT-StarterProject-Public#2]
**Модуль 1**

- [ ] [1. Как разработчик, мне нужно настроить и подготовить проект к работе](https://github.com/users/mocki-toki/projects/2/views/10?pane=issue&itemId=90821199)
- [ ] [2. Как пользователь, я хочу видеть добавленные товары в корзину с их изображением, названием, ценой, кнопкой удаления и рейтингом, чтобы понимать, что я собираюсь купить (мок-данные)](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/16)
- [ ] [3. Как пользователь, я хочу видеть сообщение «Корзина пуста», если в корзине нет товаров, чтобы понимать её состояние](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/17)
- [ ] [4. Как пользователь, я хочу иметь возможность работать с реальными данными](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/18)

**Модуль 2**
- [ ] [1. Как пользователь, я хочу иметь возможность сортировать товары в корзине по цене, названию или рейтингу](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/19)
- [ ] [2. Как пользователь, я хочу, чтобы выбранный способ сортировки сохранялся, даже если я закрою приложение, чтобы не настраивать его заново](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/20)
- [ ] [3. Как пользователь, я хочу иметь возможность удалить товар из корзины](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/21)

**Модуль 3**
- [ ] [1. Как пользователь, я хочу видеть общую стоимость товаров в корзине и их количество, чтобы понимать, сколько мне нужно заплатить](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/22)
- [ ] [2. Как пользователь, я хочу выбрать способ оплаты из списка доступных валют, чтобы совершить оплату в удобной валюте](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/23)
- [ ] [3. Как владелец, я хочу, чтобы пользователь имел возможность прочесть пользовательское соглашение перед оплатой](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/24)
- [ ] [4. Как пользователь, я хочу видеть сообщение об успешной оплате с поздравлением, чтобы убедиться, что всё прошло хорошо](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/25)
- [ ] [5. Как пользователь, я хочу получить сообщение об ошибке оплаты с возможностью повторить попытку, чтобы завершить покупку](https://github.com/mocki-toki/iOS-FakeNFT-StarterProject-Public/issues/26)
